spritesheet:
  name: kennynl
  px_total: 768
  py_total: 352
  px: 16
  py: 16
  nx: 48
  ny: 22
sprites:
  - name: EMPTY
    x: 0
    y: 0
  - name: BUSH_0
    x: 1
    y: 0
  - name: BUSH_1
    x: 2
    y: 0
  - name: BUSH_2
    x: 3
    y: 0
  - name: BUSH_3
    x: 4
    y: 0
  - name: BUSH_4
    x: 5
    y: 0
  - name: BUSH_5
    x: 6
    y: 0
  - name: BUSH_6
    x: 7
    y: 0
  - name: PERSON_0
    x: 24
    y: 0
  - name: PERSON_1
    x: 25
    y: 0
  - name: PERSON_2
    x: 26
    y: 0
  - name: PERSON_3
    x: 27
    y: 0
  - name: PERSON_4
    x: 28
    y: 0
  - name: PERSON_5
    x: 29
    y: 0
  - name: PERSON_6
    x: 30
    y: 0
  - name: PERSON_7
    x: 31
    y: 0
  - name: TREE_1
    x: 0
    y: 1
  - name: TREE_2
    x: 1
    y: 1
  - name: TREE_3
    x: 2
    y: 1
  - name: TREE_4
    x: 3
    y: 1
  - name: TREE_5
    x: 4
    y: 1
  - name: TREE_6
    x: 5
    y: 1
  - name: TREE_7
    x: 6
    y: 1
  - name: TREE_8
    x: 7
    y: 1
  - name: CASTLE_FLOOR
    x: 19
    y: 1
  - name: WALL_BIG
    x: 2
    y: 3
  - name: WEAPON_ARROW_1
    x: 40
    y: 5
    angle: -45.0
  - name: WEAPON_ARROW_2
    x: 41
    y: 5
    angle: -45.0
  - name: WEAPON_SHOVEL
    x: 42
    y: 5
    angle: -45.0
  - name: WEAPON_PICKAXE
    x: 42
    y: 5
    angle: -30.0
  - name: ORC
    x: 30
    y: 6
  - name: WEAPON_DAGGER_OUTLINED_1
    x: 32
    y: 6
    angle: -45.0
  - name: WEAPON_DAGGER_SOLID_3
    x: 34
    y: 6
    angle: -45.0
  - name: WEAPON_PISTOL
    x: 37
    y: 9
  - name: WEAPON_RAY_PISTOL
    x: 38
    y: 9
  - name: WEAPON_SHOTGUN
    x: 39
    y: 9
  - name: WEAPON_SUB_MACHINE_GUN
    x: 40
    y: 9
  - name: WEAPON_MINI_UZI
    x: 41
    y: 9
  - name: WEAPON_MP5
    x: 42
    y: 9
  - name: WEAPON_RPG
    x: 43
    y: 9
  - name: AMMO_BOX
    x: 44
    y: 9
  - name: CAMPFIRE
    x: 14
    y: 10
  - name: FIRE
    x: 15
    y: 10
  - name: ICON_HEART
    x: 39
    y: 10
  - name: ICON_HEART_OUTLINE
    x: 40
    y: 10
  - name: ICON_HEART_HALF_FULL
    x: 41
    y: 10
  - name: ICON_HEART_FULL
    x: 42
    y: 10
  - name: SKULL_AND_BONES
    x: 0
    y: 15
  - name: NUMBER_0
    x: 35
    y: 17
  - name: NUMBER_1
    x: 36
    y: 17
  - name: NUMBER_2
    x: 37
    y: 17
  - name: NUMBER_3
    x: 38
    y: 17
  - name: NUMBER_4
    x: 39
    y: 17
  - name: NUMBER_5
    x: 40
    y: 17
  - name: NUMBER_6
    x: 41
    y: 17
  - name: NUMBER_7
    x: 42
    y: 17
  - name: NUMBER_8
    x: 43
    y: 17
  - name: NUMBER_9
    x: 44
    y: 17
  - name: BOAT
    x: 10
    y: 19
  - name: SPACE_VEHICLE_1
    x: 12
    y: 21
  - name: SPACE_VEHICLE_2
    x: 13
    y: 21
  - name: SPACE_VEHICLE_3
    x: 14
    y: 21
  - name: FIREWORK
    x: 32
    y: 21
  - name: ROCKET_1
    x: 33
    y: 21
  - name: ROCKET_2
    x: 34
    y: 21
